export const MOVIMENTACAO_CREATE_BEGIN = 'MOVIMENTACAO_CREATE_BEGIN';
export const MOVIMENTACAO_CREATE_SUCCESS = 'MOVIMENTACAO_CREATE_SUCCESS';
export const MOVIMENTACAO_CREATE_ERROR = 'MOVIMENTACAO_CREATE_ERROR';

export const MOVIMENTACAO_CLEAR_BEGIN = 'MOVIMENTACAO_CLEAR_BEGIN';
export const MOVIMENTACAO_CLEAR_END = 'MOVIMENTACAO_CLEAR_END';
