export const USUARIO_CREATE_BEGIN = 'USUARIO_CREATE_BEGIN';
export const USUARIO_CREATE_SUCCESS = 'USUARIO_CREATE_SUCCESS';
export const USUARIO_CREATE_ERROR = 'USUARIO_CREATE_ERROR';

export const USUARIO_CLEAR_BEGIN = 'USUARIO_CLEAR_BEGIN';
export const USUARIO_CLEAR_END = 'USUARIO_CLEAR_END';
